### ISSUE TITLE
Cadastrar Turma

### ISSUE THREAD

**Issue by lucasnobredev** [losnoblesdevs/minos#6]
Assim como já criaram o cadastro de Professor, cadastrem Turma. Pensem na regra de negócio e criem os cenários de teste em cima. A cada ideia que forem tendo, vão adicionando o checklist aqui.

Checklist:
- [x] Cadastro de Turmas.
- [x] Validação do Cadastro.
- [x] Cenários de Teste.
- [x] Não permitir que series acessam graus fora de seu seguimento.
- [x] Gerador de CodigoTurma.

**Comment by eneaslucas** [comment]
Estou tendo dificuldades para conseguir associar TurmaId com Turmas .

**Comment by eneaslucas** [comment]
Tudo completo .
